### PR TITLE
docs: Explicitely mention compatibility and link to more information

### LINKED ISSUE #7: Clarify interoperability with original signify
Does signify-rs intend to interop with the original signify?

If so, I suggest you:
- State explicitly that signify-rs verifies signatures generated by BSD signify and signs data in a format that BSD signify can verify.
- Link to https://www.openbsd.org/papers/bsdcan-signify.html so that people who aren't familiar with signify can become familiar with the concept.
- Get signify-rs added to the "Other Implementations" section of https://github.com/aperezdc/signify#other-implementations.

### PR DESCRIPTION
**Pull request by badboy**
Closes #7

### CODE REVIEW

**Comment by badboy** [comment]
@not-a-robot r+

**Comment by ghost** [comment]
:pushpin: Commit 8af4a29 has been approved by `badboy`

**Comment by ghost** [comment]
:hourglass: Testing commit 8af4a29 with merge c5a8193...

**Comment by ghost** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/badboy/signify-rs/builds/160813053)
Approved by: badboy
Pushing c5a8193cee7436587144e44a63722e87ef52b86c to master...

**Pull request merged**
