### PR TITLE
Update lockfile

### PR DESCRIPTION
**Pull request by badboy**

### CODE REVIEW

**Comment by badboy** [comment]
@not-a-robot r+

**Comment by ghost** [comment]
:pushpin: Commit a1abbbe has been approved by `badboy`

**Comment by ghost** [comment]
:hourglass: Testing commit a1abbbe with merge c76f7c0...

**Comment by badboy** [comment]
@not-a-robot r+

**Comment by ghost** [comment]
:pushpin: Commit 0d228f4 has been approved by `badboy`

**Comment by ghost** [comment]
:hourglass: Testing commit 0d228f4 with merge d028481...

**Comment by ghost** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/badboy/signify-rs/builds/177304445)
Approved by: badboy
Pushing d02848126bd1d24ceb73bf2487f290f9566a326f to master...

**Pull request merged**
