### PR TITLE
Fail on exist

### PR DESCRIPTION
**Pull request by badboy**

### CODE REVIEW

**Comment by badboy** [comment]
@not-a-robot r+

**Comment by ghost** [comment]
:pushpin: Commit 0202e35 has been approved by `badboy`

**Comment by ghost** [comment]
:hourglass: Testing commit 0202e35 with merge 0eca338...

**Comment by ghost** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/badboy/signify-rs/builds/140568047)
Approved by: badboy
Pushing 0eca338d47810332383073fab4d332addd606635 to master...

**Pull request merged**
