### PR TITLE
tests: Check output works with original signify

### PR DESCRIPTION
**Pull request by badboy**

### CODE REVIEW

**Comment by badboy** [comment]
@not-a-robot r+

**Comment by ghost** [comment]
:pushpin: Commit 29d8a8e has been approved by `badboy`

**Comment by ghost** [comment]
:hourglass: Testing commit 29d8a8e with merge d5ed4cb...

**Comment by ghost** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/badboy/signify-rs/builds/140578767)
Approved by: badboy
Pushing d5ed4cba9811bf702cb74112035e26318c6c7449 to master...

**Pull request merged**
