### PR TITLE
With ring

### PR DESCRIPTION
**Pull request by badboy**
On request from @briansmith, I decided to port over signify-rs to use ring.

I replaced rust-crypto with ring for all ed25519 operations.
rust-crypto is still in there, as it provides the bcrypt pbkdf (which is the one used by the original signify)

### CODE REVIEW

**Comment by badboy** [comment]
Merging this in order to push out a new release now.
I also want to write a short blog post.

I'd really like to get rid of rust-crypto eventually.

@not-a-robot r+

**Comment by ghost** [comment]
:pushpin: Commit a388445 has been approved by `badboy`

**Comment by ghost** [comment]
:hourglass: Testing commit a388445 with merge 8b1a347...

**Comment by ghost** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/badboy/signify-rs/builds/163064216)
Approved by: badboy
Pushing 8b1a347e6703b01e083a2f8743e7d8b40b35497e to master...

**Pull request merged**
