### PR TITLE
Trust

### PR DESCRIPTION
**Pull request by badboy**

### CODE REVIEW

**Comment by badboy** [comment]
bors try

**Comment by badboy** [comment]
bors try

**Comment by badboy** [comment]
bors try

**Comment by badboy** [comment]
bors try

**Comment by badboy** [comment]
bors try

**Comment by badboy** [comment]
bors try

**Comment by notriddle** [comment]
Maybe you should raise the timeout in bors.toml?

**Comment by badboy** [comment]
@notriddle I should. How do I configure it?

**Comment by notriddle** [comment]
Probably write this in `bors.toml`:

```toml
# Gate on Travis CI and AppVeyor
status = [
  "continuous-integration/travis-ci/push",
  "continuous-integration/appveyor/branch",
]
# Set bors's timeout to 4 hours
timeout-sec = 14400
```

https://forum.bors.tech/t/bors-keeps-timing-out/87

**Comment by badboy** [comment]
Thanks. Will take care of this later.

**Comment by notriddle** [comment]
appveyor isn't building the staging branch

**Comment by badboy** [comment]
I'm still bad at it it seems

**Comment by badboy** [comment]
It worked! \o/
Thanks @notriddle

**Pull request merged**
