### PR TITLE
chore: Add clippy badge

### PR DESCRIPTION
**Pull request by badboy**

### CODE REVIEW

**Comment by badboy** [comment]
@not-a-robot r+

**Comment by ghost** [comment]
:pushpin: Commit 3caf27a has been approved by `badboy`

**Comment by ghost** [comment]
:hourglass: Testing commit 3caf27a with merge 3e04a68...

**Comment by badboy** [comment]
@not-a-robot r-

**Comment by badboy** [comment]
Somehow broken currently.

**Pull request closed without merging**
