### PR TITLE
chore(CI): Test on OSX as well

### PR DESCRIPTION
**Pull request by badboy**

### CODE REVIEW

**Comment by badboy** [comment]
@not-a-robot r+

**Comment by ghost** [comment]
:pushpin: Commit c7b93af has been approved by `badboy`

**Comment by ghost** [comment]
:hourglass: Testing commit c7b93af with merge d5dba01...

**Comment by ghost** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/badboy/signify-rs/builds/140406316)

**Comment by badboy** [comment]
@not-a-robot r+

**Comment by ghost** [comment]
:pushpin: Commit 189b227 has been approved by `badboy`

**Comment by ghost** [comment]
:hourglass: Testing commit 189b227 with merge 67fe2ad...

**Comment by badboy** [comment]
@not-a-robot r+

**Comment by ghost** [comment]
:pushpin: Commit 9852f4d has been approved by `badboy`

**Comment by ghost** [comment]
:hourglass: Testing commit 9852f4d with merge b7027ae...

**Comment by ghost** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/badboy/signify-rs/builds/140411566)
Approved by: badboy
Pushing b7027aeb9c087421544b21ebeee36a0b0ee0542b to master...

**Pull request merged**
