### PR TITLE
chore: Enable Windows CI

### PR DESCRIPTION
**Pull request by badboy**

### CODE REVIEW

**Comment by badboy** [comment]
@not-a-robot r+

**Comment by ghost** [comment]
:pushpin: Commit 1eee6fc has been approved by `badboy`

**Comment by badboy** [comment]
@not-a-robot r+

**Comment by ghost** [comment]
:pushpin: Commit c7a6a9e has been approved by `badboy`

**Comment by ghost** [comment]
:hourglass: Testing commit c7a6a9e with merge a970c35...

**Comment by ghost** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/badboy/signify-rs/builds/140413241)
Approved by: badboy
Pushing a970c35027ad00bdc3630d48bdc714ed9dc49e46 to master...

**Pull request merged**
